SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

USE `jaus` ;

INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,1,'Álava');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,2,'Albacete');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,3,'Alicante');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,4,'Almería');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,5,'Asturias');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,6,'Ávila');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,7,'Badajoz');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,8,'Barcelona');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,9,'Burgos');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,10,'Cáceres');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,11,'Cádiz');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,12,'Cantabria');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,13,'Castellón');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,14,'Ciudad Real');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,15,'Córdoba');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,16,'La Coruña');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,17,'Cuenca');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,18,'Gerona');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,19,'Granada');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,20,'Guadalajara');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,21,'Guipúzcoa');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,22,'Huelva');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,23,'Huesca');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,24,'Baleares');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,25,'Jaén');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,26,'León');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,27,'Lérida');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,28,'Lugo');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,29,'Madrid');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,30,'Málaga');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,31,'Murcia');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,32,'Navarra');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,33,'Orense');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,34,'Palencia');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,35,'Las Palmas');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,36,'Pontevedra');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,37,'La Rioja');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,38,'Salamanca');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,39,'Segovia');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,40,'Sevilla');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,41,'Soria');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,42,'Tarragona');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,43,'Santa Cruz de Tenerife');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,44,'Teruel');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,45,'Toledo');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,46,'Valencia');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,47,'Valladolid');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,48,'Vizcaya');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,49,'Zamora');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,50,'Zaragoza');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,51,'Ceuta');
INSERT INTO provincia (idpais, idprovincia, nombreprov) VALUES (1,52,'Melilla');
